// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FirewallDemo.Model.Data;

public partial class Item
{
    public string ItemId { get; set; }

    public string ItemName { get; set; }

    public string Type { get; set; }

    public string SellerId { get; set; }

    public decimal SellPrice { get; set; }

    public string Summary { get; set; }

    public string Picture { get; set; }

    public string ItemStatus { get; set; }

    public DateTime ListingTimestamp { get; set; }

    public DateTime? DelistingTimestamp { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual User Seller { get; set; }
}