// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FirewallDemo.Model.Data;

public partial class Message
{
    public string MsgId { get; set; }

    public string ChatId { get; set; }

    public string SenderId { get; set; }

    public DateTime Timestamp { get; set; }

    public string Content { get; set; }

    public sbyte Unread { get; set; }

    public virtual ChatList Chat { get; set; }

    public virtual User Sender { get; set; }
}