// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FirewallDemo.Model.Data;

public partial class UserPrivkey
{
    public string UserId { get; set; }

    public string PrivateKey { get; set; }
}